# Generated by Django 5.1.15 on 2026-03-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimizer", "0001_initial"),
        ("prices", "0002_alter_price_source"),
        ("products", "0001_initial"),
        ("stores", "0003_store_google_place_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptimizationRouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_order", models.PositiveSmallIntegerField(verbose_name="Orden de parada")),
                (
                    "distance_km",
                    models.FloatField(default=0.0, verbose_name="Distancia desde parada previa (km)"),
                ),
                (
                    "time_minutes",
                    models.FloatField(default=0.0, verbose_name="Tiempo desde parada previa (min)"),
                ),
                (
                    "subtotal_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Subtotal de la parada",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "optimization_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="optimizer.optimizationresult",
                        verbose_name="Resultado de optimizacion",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_stops",
                        to="shopping_lists.shoppinglist",
                        verbose_name="Lista de la compra",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_stops",
                        to="stores.store",
                        verbose_name="Tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parada de optimizacion",
                "verbose_name_plural": "Paradas de optimizacion",
                "ordering": ["stop_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("optimization_result", "stop_order"),
                        name="optimizer_route_stop_unique_order",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OptimizationRouteStopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.CharField(max_length=255, verbose_name="Texto original del item")),
                (
                    "matched_product_name",
                    models.CharField(max_length=255, verbose_name="Producto asignado"),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1, verbose_name="Cantidad")),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Precio unitario"),
                ),
                (
                    "line_total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio total de linea",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(default=0.0, verbose_name="Puntuacion de similitud"),
                ),
                (
                    "candidate_rank",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Ranking candidato"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="optimization_stop_items",
                        to="prices.price",
                        verbose_name="Precio seleccionado",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="optimization_stop_items",
                        to="products.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="optimizer.optimizationroutestop",
                        verbose_name="Parada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de parada optimizada",
                "verbose_name_plural": "Items de parada optimizada",
                "ordering": ["id"],
            },
        ),
    ]
